imports:
    - { resource: config.yml }

# Contao configuration
contao:
    pretty_error_screens: true

# Monolog configuration
monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        contao:
            type: service
            id: contao.monolog.handler
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [400, 401, 403, 404, 503]
            channels: ['!deprecation']
        nested:
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        console:
            type: console
        # Do not log deprecation messages in production because they might flood the file system. If you are a developer
        # reading this and trying to get the messages logged in production in preparation for an update, checkout
        # the default configuration for the "dev" environment that is shipped with Contao for reference and adjust "prod"
        # to your needs accordingly.
        deprecation:
            type: 'null'
            channels: [deprecation]
