# Configuration for probot-stale - https://github.com/probot/stale

daysUntilStale: 60
daysUntilClose: 7

exemptLabels:
    - feature
    - up for discussion
    - help wanted
    - BC break

markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

closeComment: false
staleLabel: stale
exemptAssignees: true
