language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.monorepo-split-cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'
    - COVERAGE='--no-logging'

jobs:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.1
    - php: 7.2
      env: COVERAGE='--exclude-group contao3'

    # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

    # Lowest dependencies with the oldest and latest PHP versions
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

    # Split the monorepo
    - stage: split
      if: 'type = push AND branch =~ /^(master|\d+\.\d+)$/'
      php: 7.2
      script: php vendor/bin/monorepo-tools composer-json --validate && php vendor/bin/monorepo-tools split $TRAVIS_BRANCH --cache-dir $HOME/.monorepo-split-cache

  allow_failures:
    - php: nightly

before_install:
  - if [[ "$COVERAGE" == "--no-logging" ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  # To be removed when this is resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction --no-suggest; fi
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c calendar-bundle $COVERAGE
  - php vendor/bin/phpunit -c core-bundle $COVERAGE
  - php vendor/bin/phpunit -c faq-bundle $COVERAGE
  - php vendor/bin/phpunit -c installation-bundle $COVERAGE
  - php vendor/bin/phpunit -c manager-bundle $COVERAGE
  - php vendor/bin/phpunit -c news-bundle $COVERAGE
  - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress

after_script:
  - if [[ -e core-bundle/coverage.xml ]]; then php vendor/bin/php-coveralls -o coveralls-upload.json -x calendar-bundle/coverage.xml -x core-bundle/coverage.xml -x faq-bundle/coverage.xml -x manager-bundle/coverage.xml -x news-bundle/coverage.xml; fi
