language: php
dist: xenial

services:
    - mysql

cache:
    directories:
        - $HOME/.composer
        - $HOME/.monorepo-split-cache

env:
    global:
        - COMPOSER_ALLOW_XDEBUG=0
        - COMPOSER_MEMORY_LIMIT=-1

branches:
    only:
        - master
        - /^\d+\.\d+$/

jobs:
    include:
        - stage: test
          name: 'Test installing the split repos'
          php: 7.3
          script:
              - cd $TRAVIS_BUILD_DIR/calendar-bundle && run_split_tests
              - cd $TRAVIS_BUILD_DIR/core-bundle && run_split_tests
              - cd $TRAVIS_BUILD_DIR/faq-bundle && run_split_tests
              - cd $TRAVIS_BUILD_DIR/manager-bundle && run_split_tests
              - cd $TRAVIS_BUILD_DIR/news-bundle && run_split_tests

        - stage: test
          name: 'Test installing the lowest dependencies'
          php: 7.3
          install:
              - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
          script:
              - php vendor/bin/simple-phpunit
              - php vendor/bin/simple-phpunit --testsuite=functional
              - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
              - php vendor/bin/monorepo-tools composer-json --validate

        - stage: test
          php: 7.2
          install:
              - composer update --no-interaction --no-suggest
          script:
              - php vendor/bin/simple-phpunit
              - php vendor/bin/simple-phpunit --testsuite=functional
              - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
              - php vendor/bin/monorepo-tools composer-json --validate

        - stage: test
          php: 7.3
          install:
              - composer update --no-interaction --no-suggest
          script:
              - php vendor/bin/simple-phpunit
              - php vendor/bin/simple-phpunit --testsuite=functional
              - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
              - php vendor/bin/monorepo-tools composer-json --validate

        - stage: test
          if: 'type = cron'
          php: 7.4snapshot
          install:
              - composer update --no-interaction --no-suggest
          script:
              - php vendor/bin/simple-phpunit
              - php vendor/bin/simple-phpunit --testsuite=functional
              - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
              - php vendor/bin/monorepo-tools composer-json --validate

        # Ignore the platform requirements for the upcoming PHP version
        - stage: test
          if: 'type = cron'
          php: nightly
          install:
              - composer update --ignore-platform-reqs --no-interaction --no-suggest
          script:
              - php vendor/bin/simple-phpunit
              - php vendor/bin/simple-phpunit --testsuite=functional
              - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
              - php vendor/bin/monorepo-tools composer-json --validate

        # Split the monorepo
        - stage: split
          name: 'Split the monorepo'
          if: 'type = push AND (branch =~ /^(master|\d+\.\d+)$/ OR tag IS present)'
          php: 7.3
          install:
              - update_composer_json
              - composer update --no-interaction --no-suggest
          script:
              - php vendor/bin/monorepo-tools split $TRAVIS_BRANCH --cache-dir $HOME/.monorepo-split-cache

    allow_failures:
        - php: 7.4snapshot
        - php: nightly

before_install:
    - |
      # Helper functions
      run_split_tests () {
        php -r '
          $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
          if ("contao/core-bundle" !== $data["name"]) {
            $data["repositories"][0]["type"] = "path";
            $data["repositories"][0]["url"] = "../core-bundle";
          }
          if ("contao/installation-bundle" !== $data["name"]) {
            $data["repositories"][1]["type"] = "path";
            $data["repositories"][1]["url"] = "../installation-bundle";
          }
          file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
        '
        COMPOSER_ROOT_VERSION=dev-$TRAVIS_COMMIT composer update --no-interaction --no-suggest
        php vendor/bin/simple-phpunit --colors=always
      }
      update_composer_json () {
        php -r '
          $data = ["require" => ["contao/monorepo-tools" => "dev-master"]];
          file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
        '
      }
    - phpenv config-rm xdebug.ini || true
    - composer global require symfony/flex
    - mysql -e "CREATE database contao_test"
