#!/usr/bin/env bash

function phpunit() {
  if [[ ! -e ./vendor/bin/simple-phpunit ]]; then
    echo "The vendor/bin/simple-phpunit file is missing. Did you install the dependencies?"
    exit 1
  fi

  vendor/bin/simple-phpunit "$@"
}

function functional() {
  if [[ ! -e ./vendor/bin/simple-phpunit ]]; then
    echo "The vendor/bin/simple-phpunit file is missing. Did you install the dependencies?"
    exit 1
  fi

  vendor/bin/simple-phpunit --testsuite=functional  "$@"
}

function php-cs-fixer() {
  if [[ ! -e ./vendor/bin/php-cs-fixer ]]; then
    echo "The vendor/bin/php-cs-fixer file is missing. Did you install the dependencies?"
    exit 1
  fi

  vendor/bin/php-cs-fixer fix -v "$@"
  PHP_CS_CONFIG=legacy vendor/bin/php-cs-fixer fix -v "$@"
  PHP_CS_CONFIG=template vendor/bin/php-cs-fixer fix -v "$@"
}

function phpstan() {
  if [[ ! -e ./vendor/bin/phpstan ]]; then
    echo "The vendor/bin/phpstan file is missing. Did you install the dependencies?"
    exit 1
  fi

  vendor/bin/phpstan analyze core-bundle/src core-bundle/tests --level=3
}

function composer() {
  if [[ ! -e ./vendor/bin/monorepo-tools ]]; then
    echo "The vendor/bin/monorepo-tools file is missing. Did you install the dependencies?"
    exit 1
  fi

  vendor/bin/monorepo-tools composer --validate
}

function usage() {
  cat <<HEREDOC
Usage: ./run [task]
  phpunit       Run the unit tests
  functional    Run the functional tests
  php-cs-fixer  Run the PHP coding style fixer
  phpstan       Run the static PHP analyzer
  composer      Validate the composer.json files
HEREDOC
}

case "$1" in
  phpunit)
    phpunit "${@:2}"
    exit 0
  ;;
  functional)
    functional "${@:2}"
    exit 0
  ;;
  php-cs-fixer)
    php-cs-fixer "${@:2}"
    exit 0
  ;;
  phpstan)
    phpstan
    exit 0
  ;;
  composer)
    composer
    exit 0
  ;;
  all)
    phpunit "${@:2}"
    functional "${@:2}"
    php-cs-fixer "${@:2}"
    phpstan
    composer
    exit 0
  ;;
  *)
    usage
    exit 1
  ;;
esac
