<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\CoreBundle\Doctrine\Backup\Config;

use Contao\CoreBundle\Doctrine\Backup\Backup;

abstract class AbstractConfig
{
    public const DEFAULT_DUMP_HEADER = '-- Generated by the Contao Open Source CMS Backup Manager (version: v1).';
    private Backup $backup;
    private string $dumpHeader;
    private array $tablesToIgnore = [];
    private bool $gzCompression;

    public function __construct(Backup $backup)
    {
        $this->backup = $backup;
        $this->dumpHeader = self::DEFAULT_DUMP_HEADER;

        // Enable gz compression by default if path ends on .gz
        $this->gzCompression = 0 === strcasecmp(substr($backup->getFilepath(), -3), '.gz');
    }

    public function getTablesToIgnore(): array
    {
        return $this->tablesToIgnore;
    }

    public function getBackup(): Backup
    {
        return $this->backup;
    }

    public function isGzCompressionEnabled(): bool
    {
        return $this->gzCompression;
    }

    public function getDumpHeader(): string
    {
        return $this->dumpHeader;
    }

    public function withGzCompression(bool $enable): self
    {
        $new = clone $this;
        $new->gzCompression = $enable;

        return $new;
    }

    public function withTablesToIgnore(array $tablesToIgnore): self
    {
        $new = clone $this;
        $new->tablesToIgnore = $tablesToIgnore;

        return $new;
    }

    public function withFilePath(string $filePath): self
    {
        $new = clone $this;
        $new->backup = new Backup($filePath);

        return $new;
    }

    public function withDumpHeader(string $dumpHeader): self
    {
        $new = clone $this;
        $new->dumpHeader = $dumpHeader;

        return $new;
    }
}
