<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\CoreBundle\EventListener\DataContainer;

use Contao\CoreBundle\DependencyInjection\Attribute\AsCallback;
use Contao\DataContainer;

class HighlightLanguageListener
{
    public const array ACE_MODES = [
        'apache' => 'apache_conf',
        'bash' => 'sh',
        'c' => 'c_cpp',
        'cpp' => 'c_cpp',
        'csharp' => 'csharp',
        'css' => 'css',
        'diff' => 'diff',
        'go' => 'golang',
        'groovy' => 'groovy',
        'ini' => 'ini',
        'java' => 'java',
        'javascript' => 'javascript',
        'json' => 'json',
        'markdown' => 'markdown',
        'nginx' => 'nginx',
        'perl' => 'perl',
        'php' => 'php',
        'powershell' => 'powershell',
        'python' => 'python',
        'ruby' => 'ruby',
        'scala' => 'scala',
        'scss' => 'scss',
        'sql' => 'sql',
        'twig' => 'twig',
        'typescript' => 'typescript',
        'xml' => 'xml',
        'yaml' => 'yaml',
    ];

    public const array LANGUAGES = [
        '1c' => '1C:Enterprise',
        'abnf' => 'Augmented Backus-Naur Form',
        'accesslog' => 'Apache Access Log',
        'actionscript' => 'ActionScript',
        'ada' => 'Ada',
        'angelscript' => 'AngelScript',
        'apache' => 'Apache config',
        'applescript' => 'AppleScript',
        'arcade' => 'ArcGIS Arcade',
        'arduino' => 'Arduino',
        'armasm' => 'ARM Assembly',
        'asciidoc' => 'AsciiDoc',
        'aspectj' => 'AspectJ',
        'autohotkey' => 'AutoHotkey',
        'autoit' => 'AutoIt',
        'avrasm' => 'AVR Assembly',
        'awk' => 'Awk',
        'axapta' => 'X++',
        'bash' => 'Bash',
        'basic' => 'BASIC',
        'bnf' => 'Backus-Naur Form',
        'brainfuck' => 'Brainfuck',
        'c' => 'C',
        'cal' => 'C/AL',
        'capnproto' => 'Cap\'n Proto',
        'ceylon' => 'Ceylon',
        'clean' => 'Clean',
        'clojure' => 'Clojure',
        'clojure-repl' => 'Clojure REPL',
        'cmake' => 'CMake',
        'coffeescript' => 'CoffeeScript',
        'coq' => 'Coq',
        'cos' => 'Caché Object Script',
        'cpp' => 'C++',
        'crmsh' => 'crmsh',
        'crystal' => 'Crystal',
        'csharp' => 'C#',
        'csp' => 'CSP',
        'css' => 'CSS',
        'd' => 'D',
        'dart' => 'Dart',
        'delphi' => 'Delphi',
        'diff' => 'Diff',
        'django' => 'Django',
        'dns' => 'DNS Zone',
        'dockerfile' => 'Dockerfile',
        'dos' => 'Batch file (DOS)',
        'dsconfig' => 'dsconfig',
        'dts' => 'Device Tree',
        'dust' => 'Dust',
        'ebnf' => 'Extended Backus-Naur Form',
        'elixir' => 'Elixir',
        'elm' => 'Elm',
        'erb' => 'ERB',
        'erlang' => 'Erlang',
        'erlang-repl' => 'Erlang REPL',
        'excel' => 'Excel formulae',
        'fix' => 'FIX',
        'flix' => 'Flix',
        'fortran' => 'Fortran',
        'fsharp' => 'F#',
        'gams' => 'GAMS',
        'gauss' => 'GAUSS',
        'gcode' => 'G-code (ISO 6983)',
        'gherkin' => 'Gherkin',
        'glsl' => 'GLSL',
        'gml' => 'GML',
        'go' => 'Go',
        'golo' => 'Golo',
        'gradle' => 'Gradle',
        'graphql' => 'GraphQL',
        'groovy' => 'Groovy',
        'haml' => 'HAML',
        'handlebars' => 'Handlebars',
        'haskell' => 'Haskell',
        'haxe' => 'Haxe',
        'hsp' => 'HSP',
        'http' => 'HTTP',
        'hy' => 'Hy',
        'inform7' => 'Inform 7',
        'ini' => 'TOML, also INI',
        'irpf90' => 'IRPF90',
        'isbl' => 'ISBL',
        'java' => 'Java',
        'javascript' => 'JavaScript',
        'jboss-cli' => 'JBoss CLI',
        'json' => 'JSON',
        'julia' => 'Julia',
        'julia-repl' => 'Julia REPL',
        'kotlin' => 'Kotlin',
        'lasso' => 'Lasso',
        'latex' => 'LaTeX',
        'ldif' => 'LDIF',
        'leaf' => 'Leaf',
        'less' => 'Less',
        'lisp' => 'Lisp',
        'livecodeserver' => 'LiveCode',
        'livescript' => 'LiveScript',
        'llvm' => 'LLVM IR',
        'lsl' => 'LSL (Linden Scripting Language)',
        'lua' => 'Lua',
        'makefile' => 'Makefile',
        'markdown' => 'Markdown',
        'mathematica' => 'Mathematica',
        'matlab' => 'Matlab',
        'maxima' => 'Maxima',
        'mel' => 'MEL',
        'mercury' => 'Mercury',
        'mipsasm' => 'MIPS Assembly',
        'mizar' => 'Mizar',
        'mojolicious' => 'Mojolicious',
        'monkey' => 'Monkey',
        'moonscript' => 'MoonScript',
        'n1ql' => 'N1QL',
        'nestedtext' => 'Nested Text',
        'nginx' => 'Nginx config',
        'nim' => 'Nim',
        'nix' => 'Nix',
        'node-repl' => 'Node REPL',
        'nsis' => 'NSIS',
        'objectivec' => 'Objective-C',
        'ocaml' => 'OCaml',
        'openscad' => 'OpenSCAD',
        'oxygene' => 'Oxygene',
        'parser3' => 'Parser3',
        'perl' => 'Perl',
        'pf' => 'Packet Filter config',
        'pgsql' => 'PostgreSQL',
        'php' => 'PHP',
        'php-template' => 'PHP template',
        'plaintext' => 'Plain text',
        'pony' => 'Pony',
        'powershell' => 'PowerShell',
        'processing' => 'Processing',
        'profile' => 'Python profiler',
        'prolog' => 'Prolog',
        'properties' => '.properties',
        'protobuf' => 'Protocol Buffers',
        'puppet' => 'Puppet',
        'purebasic' => 'PureBASIC',
        'python' => 'Python',
        'python-repl' => 'Python REPL',
        'q' => 'Q',
        'qml' => 'QML',
        'r' => 'R',
        'reasonml' => 'ReasonML',
        'rib' => 'RenderMan RIB',
        'roboconf' => 'Roboconf',
        'routeros' => 'MikroTik RouterOS script',
        'rsl' => 'RenderMan RSL',
        'ruby' => 'Ruby',
        'ruleslanguage' => 'Oracle Rules Language',
        'rust' => 'Rust',
        'sas' => 'SAS',
        'scala' => 'Scala',
        'scheme' => 'Scheme',
        'scilab' => 'Scilab',
        'scss' => 'SCSS',
        'shell' => 'Shell Session',
        'smali' => 'Smali',
        'smalltalk' => 'Smalltalk',
        'sml' => 'SML (Standard ML)',
        'sqf' => 'SQF',
        'sql' => 'SQL',
        'stan' => 'Stan',
        'stata' => 'Stata',
        'step21' => 'STEP Part 21',
        'stylus' => 'Stylus',
        'subunit' => 'SubUnit',
        'swift' => 'Swift',
        'taggerscript' => 'Tagger Script',
        'tap' => 'Test Anything Protocol',
        'tcl' => 'Tcl',
        'thrift' => 'Thrift',
        'tp' => 'TP',
        'twig' => 'Twig',
        'typescript' => 'TypeScript',
        'vala' => 'Vala',
        'vbnet' => 'Visual Basic .NET',
        'vbscript' => 'VBScript',
        'vbscript-html' => 'VBScript in HTML',
        'verilog' => 'Verilog',
        'vhdl' => 'VHDL',
        'vim' => 'Vim Script',
        'wasm' => 'WebAssembly',
        'wren' => 'Wren',
        'x86asm' => 'Intel x86 Assembly',
        'xl' => 'XL',
        'xml' => 'HTML, XML',
        'xquery' => 'XQuery',
        'yaml' => 'YAML',
        'zephir' => 'Zephir',
    ];

    #[AsCallback(table: 'tl_content', target: 'fields.highlight.options')]
    public function getLanguages(): array
    {
        $languages = self::LANGUAGES;
        asort($languages);

        return $languages;
    }

    #[AsCallback(table: 'tl_content', target: 'fields.code.load')]
    public function setRteSyntax(mixed $value, DataContainer $dc): mixed
    {
        $syntax = self::ACE_MODES[$dc->getCurrentRecord()['hightlight'] ?? null] ?? 'text';

        if ('markdown' === $dc->getCurrentRecord()['type'] ?? null) {
            $syntax = 'markdown';
        }

        $GLOBALS['TL_DCA']['tl_content']['fields']['code']['eval']['rte'] = 'ace|'.$syntax;

        return $value;
    }
}
