services:
    Contao\CalendarBundle\EventListener\GeneratePageListener:
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'
        public: true

    Contao\CalendarBundle\EventListener\InsertTagsListener:
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'
        public: true

    Contao\CalendarBundle\EventListener\PreviewUrlCreateListener:
        arguments:
            - '@request_stack'
            - '@Contao\CoreBundle\Framework\ContaoFramework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    Contao\CalendarBundle\EventListener\PreviewUrlConvertListener:
        arguments:
            - '@request_stack'
            - '@Contao\CoreBundle\Framework\ContaoFramework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_convert, method: onPreviewUrlConvert }
