api_platform:
    resource: .
    type: api_platform
    prefix: '%contao.backend.route_prefix%/api'
    stateless: true
    defaults:
        _scope: backend

api_doc:
    path: '%contao.backend.route_prefix%/api/docs.{_format}'
    controller: api_platform.action.documentation
    methods: [GET, HEAD]
    stateless: false
    defaults:
        _format: null
        _api_respond: true
