services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    contao_news.picker.news_provider:
        class: Contao\NewsBundle\Picker\NewsPickerProvider
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@security.helper'
        tags:
            - { name: contao.picker_provider, priority: 128 }

    contao_news.security.news_archive_voter:
        class: Contao\NewsBundle\Security\NewsArchiveAccessVoter
        tags:
            - { name: 'security.voter' }

    contao_news.security.news_voter:
        class: Contao\NewsBundle\Security\NewsAccessVoter
        arguments:
            - '@contao.security.access_decision_manager'
            - '@contao.framework'
        tags:
            - { name: 'security.voter' }
