services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Security\Voter\AbstractFrontendAccessVoter:
            calls:
                - [setContainer, ['@Psr\Container\ContainerInterface']]

    Contao\NewsBundle\Security\Voter\:
        resource: ../../Security/Voter/*
