services:
    contao_maker.config.xliff_merger:
        class: Contao\MakerBundle\Config\XliffMerger

    contao_maker.generator.template:
        class: Contao\MakerBundle\Generator\TemplateGenerator
        arguments:
            - '@maker.generator'

    contao_maker.generator.class:
        class: Contao\MakerBundle\Generator\ClassGenerator
        arguments:
            - '@maker.generator'

    contao_maker.generator.dca:
        class: Contao\MakerBundle\Generator\DcaGenerator
        arguments:
            - '@filesystem'
            - '@maker.file_manager'
            - '%kernel.project_dir%'

    contao_maker.generator.language_file:
        class: Contao\MakerBundle\Generator\LanguageFileGenerator
        arguments:
            - '@maker.file_manager'
            - '@filesystem'
            - '@contao_maker.config.xliff_merger'
            - '%kernel.project_dir%'

    contao_maker.reflection.import_extractor:
        class: Contao\MakerBundle\Reflection\ImportExtractor

    contao_maker.reflection.signature_generator:
        class: Contao\MakerBundle\Reflection\SignatureGenerator
