services:
    contao_maker.generator.template:
        class: Contao\MakerBundle\Generator\TemplateGenerator
        arguments:
            - '@maker.generator'

    contao_maker.generator.class:
        class: Contao\MakerBundle\Generator\ClassGenerator
        arguments:
            - '@maker.generator'

    contao_maker.generator.dca:
        class: Contao\MakerBundle\Generator\DcaGenerator
        arguments:
            - '@filesystem'
            - '@maker.file_manager'
            - '%kernel.project_dir%'

    contao_maker.generator.language_file:
        class: Contao\MakerBundle\Generator\LanguageFileGenerator
        arguments:
            - '@maker.file_manager'
            - '@filesystem'
            - '@contao_maker.translation.xliff_merger'
            - '%kernel.project_dir%'

    contao_maker.import_extractor:
        class: Contao\MakerBundle\ImportExtractor

    contao_maker.signature_generator:
        class: Contao\MakerBundle\SignatureGenerator

    contao_maker.translation.xliff_merger:
        class: Contao\MakerBundle\Translation\XliffMerger
