services:
    _defaults:
        autoconfigure: true

    Contao\ManagerBundle\Controller\DebugController:
        public: true
        arguments:
            - '@security.helper'
            - '@request_stack'
            - '@contao_manager.jwt_manager'

    Contao\ManagerBundle\Controller\FrontendModule\MaintenanceLoginController:
        arguments:
            - '@request_stack'
            - '@contao.csrf.token_manager'
            - '@?contao_manager.jwt_manager'
        tags:
            - { name: contao.frontend_module, category: application }
