services:
    Contao\ManagerBundle\EventListener\BackendMenuListener:
        arguments:
            - '@Symfony\Component\Security\Core\Security'
            - '%contao_manager.manager_path%'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, method: onBuild, priority: -10 }

    Contao\ManagerBundle\EventListener\DebugListener:
        arguments:
            - '@Symfony\Component\Security\Core\Security'
            - '@request_stack'
            - '@contao_manager.jwt_manager'
        public: true

    Contao\ManagerBundle\EventListener\InitializeApplicationListener:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: contao_installation.initialize_application, method: onInitializeApplication, priority: -128 }

    Contao\ManagerBundle\EventListener\InstallCommandListener:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: console.terminate }

    Contao\ManagerBundle\EventListener\PreviewAuthenticationListener:
        arguments:
            - '@Contao\CoreBundle\Routing\ScopeMatcher'
            - '@Contao\CoreBundle\Security\Authentication\Token\TokenChecker'
            - '@router'
            - '%contao.preview_script%'
        tags:
            # The priority must be lower than the one of the firewall listener (defaults to 8)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }
