services:
    Contao\ManagerBundle\HttpKernel\JwtManager: '@contao_manager.jwt_manager'

    Contao\ManagerBundle\Cache\BundleCacheClearer:
        class: Contao\ManagerBundle\Cache\BundleCacheClearer
        arguments:
            - '@?filesystem'
        tags:
            - { name: kernel.cache_clearer }

    Contao\ManagerBundle\Routing\RouteLoader:
        arguments:
            - '@routing.loader'
            - '@contao_manager.plugin_loader'
            - '@kernel'
            - '%kernel.project_dir%'
        public: true

    Contao\ManagerBundle\Security\Logout\LogoutHandler:
        arguments:
            - '@?contao_manager.jwt_manager'

    contao_manager.plugin_loader:
        synthetic: true
        public: true

    contao_manager.jwt_manager:
        synthetic: true
        public: true
