<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\CoreBundle\BackendTheme;

interface BackendThemeInterface
{
    /**
     * Return the path to the entrypoint.json that is generated by Webpack Encore.
     * The entrypoints.json MUST contain the "app" entrypoint. All assets (CSS/JS files) defined unter this entrypoint
     * will be included into the page layout.
     *
     * Example: "web/bundles/acmecontaocustomtheme/entrypoints.json"
     *
     * The project root dir (%kernel.project_dir%) is automatically prepended to generate a absolute path.
     * Keep in mind, that the "public" folder of your bundle is automatically symlinked to "web/bundles/foobar"
     * where "foobar" is a normalized name your bundle.
     */
    public function getThemePath(): string;
}
