services:
    _defaults:
        autoconfigure: true

    Contao\InstallationBundle\Command\LockCommand:
        arguments:
            - '%kernel.project_dir%/var/install_lock'

    Contao\InstallationBundle\Command\UnlockCommand:
        arguments:
            - '%kernel.project_dir%/var/install_lock'
