services:
    Contao\InstallationBundle\InstallTool:
        arguments:
            - '@database_connection'
            - '%kernel.project_dir%'
            - '@logger'
        public: true

    Contao\InstallationBundle\InstallToolUser:
        arguments:
            - '@session'
        public: true

    Contao\InstallationBundle\Database\Installer:
        arguments:
            - '@database_connection'
            - '@contao.doctrine.schema_provider'
        public: true

    contao.install_tool_twig_extension:
        class: SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension
        tags:
            - { name: twig.extension }
