<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\CoreBundle\Tests\Doctrine\Backup;

use Contao\CoreBundle\Doctrine\Backup\Backup;
use Contao\CoreBundle\Doctrine\Backup\BackupManagerException;
use Contao\CoreBundle\Doctrine\Backup\Config\CreateConfig;
use Contao\CoreBundle\Doctrine\Backup\Dumper;
use Contao\TestCase\ContaoTestCase;
use Doctrine\DBAL\Cache\ArrayResult;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Result;
use Doctrine\DBAL\Schema\AbstractSchemaManager;
use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Filesystem\Filesystem;
use Webmozart\PathUtil\Path;

class DumperTest extends ContaoTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        (new Filesystem())->mkdir($this->getBackupDir());
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        (new Filesystem())->remove($this->getBackupDir());
    }

    /**
     * @dataProvider successfulDumpProvider
     */
    public function testSuccessfulDump(array $tables, array $queries, string $expectedDump): void
    {
        $backup = Backup::createNewAtPath(
            $this->getBackupDir(),
            \DateTime::createFromFormat(\DateTime::ISO8601, '2021-11-03T13:36:00+0000')
        );

        $connection = $this->mockConnection($tables, $queries);
        $dumper = new Dumper();
        $config = (new CreateConfig($backup))->withGzCompression(false);

        $dumper->dump($connection, $config);

        $this->assertSame($expectedDump, preg_replace('~\R~u', "\n", file_get_contents($backup->getFilepath())));
    }

    public function testIsGzipEncodedIfEnabled(): void
    {
        $backup = Backup::createNewAtPath(
            $this->getBackupDir(),
            \DateTime::createFromFormat(\DateTime::ISO8601, '2021-11-03T13:36:00+0000')
        );

        $connection = $this->mockConnection([], []);
        $dumper = new Dumper();
        $config = (new CreateConfig($backup))->withGzCompression(true);

        $dumper->dump($connection, $config);

        // Assert it's gzipped
        $this->assertTrue(0 === mb_strpos(file_get_contents($backup->getFilepath()), "\x1f"."\x8b"."\x08", 0, 'US-ASCII'));
    }

    public function testUnsuccessfulDump(): void
    {
        $this->expectException(BackupManagerException::class);
        $this->expectExceptionMessage('Error!');

        $backup = Backup::createNewAtPath(
            $this->getBackupDir(),
            \DateTime::createFromFormat(\DateTime::ISO8601, '2021-11-03T13:36:00+0000')
        );

        $connection = $this->createMock(Connection::class);
        $connection
            ->expects($this->once())
            ->method('createSchemaManager')
            ->willThrowException(new \Exception('Error!'))
        ;

        $dumper = new Dumper();
        $config = (new CreateConfig($backup))->withGzCompression(false);

        $dumper->dump($connection, $config);
    }

    public function successfulDumpProvider(): \Generator
    {
        yield 'Empty table without data' => [
            [new Table('tl_page', [new Column('foobar', Type::getType(Types::STRING))])],
            [
                'SELECT `foobar` AS `foobar` FROM `tl_page`' => [],
            ],
            <<<'DUMP'
                -- Generated by the Contao Open Source CMS Backup Manager (version: v1).
                -- Generated at 2021-11-03T13:36:00+0000
                SET NAMES utf8;
                SET FOREIGN_KEY_CHECKS = 0;
                -- BEGIN STRUCTURE tl_page
                DROP TABLE IF EXISTS `tl_page`;
                CREATE TABLE tl_page (foobar VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
                -- BEGIN DATA tl_page
                SET FOREIGN_KEY_CHECKS = 1;

                DUMP
        ];

        yield 'Table with data' => [
            [new Table('tl_page', [new Column('foobar', Type::getType(Types::STRING))])],
            [
                'SELECT `foobar` AS `foobar` FROM `tl_page`' => [
                    [
                        'foobar' => 'value1',
                    ],
                    [
                        'foobar' => null,
                    ],
                ],
            ],
            <<<'DUMP'
                -- Generated by the Contao Open Source CMS Backup Manager (version: v1).
                -- Generated at 2021-11-03T13:36:00+0000
                SET NAMES utf8;
                SET FOREIGN_KEY_CHECKS = 0;
                -- BEGIN STRUCTURE tl_page
                DROP TABLE IF EXISTS `tl_page`;
                CREATE TABLE tl_page (foobar VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
                -- BEGIN DATA tl_page
                INSERT INTO `tl_page` (`foobar`) VALUES (`value1`);
                INSERT INTO `tl_page` (`foobar`) VALUES (NULL);
                SET FOREIGN_KEY_CHECKS = 1;

                DUMP
        ];

        yield 'Multiple tables with data' => [
            [
                new Table('tl_page', [new Column('foobar', Type::getType(Types::STRING))]),
                new Table('tl_news', [new Column('foobar', Type::getType(Types::STRING))]),
            ],
            [
                'SELECT `foobar` AS `foobar` FROM `tl_page`' => [
                    [
                        'foobar' => 'value1',
                    ],
                    [
                        'foobar' => null,
                    ],
                ],
                'SELECT `foobar` AS `foobar` FROM `tl_news`' => [
                    [
                        'foobar' => 'value1',
                    ],
                ],
            ],
            <<<'DUMP'
                -- Generated by the Contao Open Source CMS Backup Manager (version: v1).
                -- Generated at 2021-11-03T13:36:00+0000
                SET NAMES utf8;
                SET FOREIGN_KEY_CHECKS = 0;
                -- BEGIN STRUCTURE tl_page
                DROP TABLE IF EXISTS `tl_page`;
                CREATE TABLE tl_page (foobar VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
                -- BEGIN DATA tl_page
                INSERT INTO `tl_page` (`foobar`) VALUES (`value1`);
                INSERT INTO `tl_page` (`foobar`) VALUES (NULL);
                -- BEGIN STRUCTURE tl_news
                DROP TABLE IF EXISTS `tl_news`;
                CREATE TABLE tl_news (foobar VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
                -- BEGIN DATA tl_news
                INSERT INTO `tl_news` (`foobar`) VALUES (`value1`);
                SET FOREIGN_KEY_CHECKS = 1;

                DUMP
        ];
    }

    /**
     * @param array $tables<Table>
     */
    private function mockConnection(array $tables, array $queries)
    {
        $schemaManager = $this->createMock(AbstractSchemaManager::class);
        $schemaManager
            ->expects($this->once())
            ->method('listTables')
            ->willReturn($tables)
        ;

        $connection = $this->createMock(Connection::class);
        $connection
            ->expects($this->once())
            ->method('createSchemaManager')
            ->willReturn($schemaManager)
        ;
        $connection
            ->method('getDatabasePlatform')
            ->willReturn(new MySQLPlatform())
        ;

        $calls = [];
        $returns = [];

        foreach ($queries as $query => $results) {
            $calls[] = [$query];
            $returns[] = new Result(new ArrayResult($results), $connection);
        }

        $connection
            ->expects($this->exactly(\count($queries)))
            ->method('executeQuery')
            ->withConsecutive(...$calls)
            ->willReturnOnConsecutiveCalls(...$returns)
        ;

        $connection
            ->method('quote')
            ->willReturnCallback(static fn ($value) => sprintf('`%s`', $value))
        ;

        return $connection;
    }

    private function getBackupDir(): string
    {
        return Path::join($this->getTempDir(), 'backups');
    }
}
