<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\ApiBundle\DataContainer;

use Contao\ApiBundle\Dto\DataContainerMove;
use Contao\ApiBundle\Dto\DataContainerRecord;
use Contao\Controller;
use Contao\CoreBundle\DataContainer\DcaRequestSwitcher;
use Contao\CoreBundle\DataContainer\DcaUrlAnalyzer;
use Contao\CoreBundle\Exception\AccessDeniedException;
use Contao\CoreBundle\Exception\ResponseException;
use Contao\CoreBundle\Framework\ContaoFramework;
use Contao\DataContainer;
use Contao\DC_Table;
use Doctrine\DBAL\Connection;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class DataContainerRecords
{
    public function __construct(
        private readonly DataContainerRecordMapper $mapper,
        private readonly Connection $connection,
        private readonly ContaoFramework $framework,
        private readonly RequestStack $requestStack,
        private readonly DcaUrlAnalyzer $urlAnalyzer,
        private readonly UrlGeneratorInterface $urlGenerator,
        private readonly DcaRequestSwitcher $requestSwitcher,
    ) {
    }

    public function find(string $table, int|string $id): DataContainerRecord|null
    {
        return $this->run(
            $table,
            ['id' => $id, 'act' => 'show'],
            function (DC_Table $dc) use ($table): DataContainerRecord|null {
                $row = $dc->getCurrentRecord();

                return null === $row ? null : $this->mapper->fromRow($table, $row);
            },
        );
    }

    public function list(string $table, int $page = 1, array $parent = []): DataContainerPage
    {
        if ($page < 1) {
            throw new UnprocessableEntityHttpException('The page must be a positive integer.');
        }

        return $this->run(
            $table,
            ['act' => 'select'] + $this->getParentParameters($parent),
            function (DC_Table $dc) use ($table, $page): DataContainerPage {
                $result = array_map(fn ($row) => $this->mapper->fromRow($table, $row), $this->getListingRecords($dc, ($page - 1) * 30));

                return new DataContainerPage($result, $page);
            },
        );
    }

    public function create(DataContainerRecord $record): DataContainerRecord
    {
        if (null !== $record->id) {
            throw new UnprocessableEntityHttpException('The record identifier is generated by the server.');
        }

        $parameters = ['act' => 'create', 'pid' => $record->data['pid'] ?? 0, 'mode' => DataContainer::PASTE_INTO_APPEND];

        if (isset($record->data['ptable'])) {
            $parameters['ptable'] = $record->data['ptable'];
        }

        return $this->write(
            $record,
            $parameters,
            function (DC_Table $dc) use ($record): DataContainerRecord {
                $response = $this->runBackendAction($dc->create(...));
                parse_str(parse_url((string) $response->headers->get('Location', ''), PHP_URL_QUERY) ?? '', $parameters);
                $id = filter_var($parameters['id'] ?? null, FILTER_VALIDATE_INT);

                if (false === $id || $id < 1 || 'edit' !== ($parameters['act'] ?? null)) {
                    throw new UnprocessableEntityHttpException('The data container did not redirect to a newly created record.');
                }

                return $this->editRecord(new DataContainerRecord($record->table, array_diff_key($record->data, array_flip(['pid', 'ptable'])), $id), true);
            },
        );
    }

    public function update(DataContainerRecord $record): DataContainerRecord
    {
        return $this->editRecord($record);
    }

    public function move(string $table, int|string $id, DataContainerMove $move): DataContainerRecord
    {
        return $this->write(
            new DataContainerRecord($table, [], $id),
            ['act' => 'cut', 'id' => $id] + $move->getParameters(),
            function (DC_Table $dc) use ($table, $move): DataContainerRecord {
                if (null === $dc->getCurrentRecord()) {
                    throw new NotFoundHttpException('The record no longer exists.');
                }

                if (null !== $move->ptable && $move->ptable !== $dc->parentTable) {
                    throw new UnprocessableEntityHttpException('The destination parent table is not supported by this data container.');
                }

                $this->validateDestination($dc, $table, $move);
                $parameters = $move->getParameters();
                $dc->cut(true, $parameters['pid'], $parameters['mode']);

                return $this->mapper->fromRow($table, $dc->getCurrentRecord());
            },
        );
    }

    public function delete(DataContainerRecord $record): void
    {
        $this->write(
            $record,
            ['act' => 'delete', 'id' => $record->id],
            static function (DC_Table $dc): void {
                if (null === $dc->getCurrentRecord()) {
                    throw new NotFoundHttpException('The record no longer exists.');
                }

                $dc->delete(true);
            },
        );
    }

    private function editRecord(DataContainerRecord $record, bool $create = false): DataContainerRecord
    {
        return $this->write(
            $record,
            ['act' => 'edit', 'id' => $record->id],
            function (DC_Table $dc) use ($record, $create): DataContainerRecord {
                $this->editWithData($dc, $record, $create);
                DataContainer::clearCurrentRecordCache($record->id, $record->table);

                return $this->mapper->fromRow($record->table, $dc->getCurrentRecord());
            },
        );
    }

    private function getListingRecords(DC_Table $dc, int $offset): array
    {
        $request = $this->requestStack->getCurrentRequest();
        $request->attributes->set('_contao_api', true);
        $request->attributes->set('_contao_listing_ids', []);

        $dc->showAll();
        $records = [];

        foreach ($request->attributes->get('_contao_listing_ids') as $id) {
            try {
                $row = $dc->getCurrentRecord($id);
            } catch (AccessDeniedException) {
                // Visible root trails can contain labels for inaccessible ancestors
                continue;
            }

            if (null === $row || $offset-- > 0) {
                continue;
            }

            $records[] = $row;

            if (30 === \count($records)) {
                break;
            }
        }

        return $records;
    }

    private function editWithData(DC_Table $dc, DataContainerRecord $record, bool $create): void
    {
        $row = $dc->getCurrentRecord();

        if (null === $row) {
            throw new NotFoundHttpException('The record no longer exists.');
        }

        // Completing an existing backend draft requires the same validation as creation
        $create = $create || 0 === (int) ($row['tstamp'] ?? 1);
        $previousFields = $create ? [] : $this->getPaletteFields($dc);
        $values = $this->mapper->toFormValues($record->table, $record->data);
        $request = $this->requestStack->getCurrentRequest();
        $main = $this->requestStack->getMainRequest();
        $previous = $request->request->all();
        $error = $main->attributes->get('_contao_widget_error');
        $main->attributes->remove('_contao_widget_error');
        $request->request->replace(['FORM_SUBMIT' => $dc->table] + $values);

        try {
            $fields = array_diff($this->getPaletteFields($dc), $previousFields, array_keys($values));

            if (!$create) {
                // Only newly active mandatory fields need defaults during a partial update
                $fields = array_filter($fields, static fn ($field) => $GLOBALS['TL_DCA'][$record->table]['fields'][$field]['eval']['mandatory'] ?? false);
            }

            $defaults = $this->mapper->toFormDefaults($record->table, $row, $fields);
            $this->submitFormValues($dc, $values, $defaults);
        } finally {
            $request->request->replace($previous);
            $main->attributes->remove('_contao_widget_error');

            if (null !== $error) {
                $main->attributes->set('_contao_widget_error', $error);
            }
        }
    }

    private function submitFormValues(DC_Table $dc, array $values, array $defaults): void
    {
        foreach (array_diff(array_keys($values), $this->getPaletteFields($dc)) as $field) {
            throw new UnprocessableEntityHttpException('Field "'.$field.'" is not available in the current palette.');
        }

        // Submit optional creation defaults too, so callbacks such as alias generation run
        $this->requestStack->getCurrentRequest()->request->add($defaults);
        $this->runBackendAction($dc->edit(...));

        if ($this->requestStack->getMainRequest()->attributes->get('_contao_widget_error')) {
            throw new UnprocessableEntityHttpException('The data container rejected the submitted fields.');
        }
    }

    private function getPaletteFields(DC_Table $dc): array
    {
        return array_values(array_filter(array_map(trim(...), preg_split('/[,;]/', $dc->getPalette())), static fn ($field) => isset($GLOBALS['TL_DCA'][$dc->table]['fields'][$field])));
    }

    private function validateDestination(DC_Table $dc, string $table, DataContainerMove $move): void
    {
        if (0 === $move->target) {
            return;
        }

        $destinationTable = 'after' === $move->position ? $table : ($dc->parentTable ?: $table);
        $destination = $dc->getCurrentRecord($move->target, $destinationTable);

        if (null === $destination) {
            throw new NotFoundHttpException('The destination record does not exist.');
        }

        if ('after' === $move->position && !empty($destination['ptable']) && $destination['ptable'] !== $dc->parentTable) {
            throw new UnprocessableEntityHttpException('Specify the destination record’s parent table when moving between dynamic parents.');
        }
    }

    private function getParentParameters(array $parent): array
    {
        $parameters = [];

        if (isset($parent['id'])) {
            $id = filter_var($parent['id'], FILTER_VALIDATE_INT, ['options' => ['min_range' => 0]]);

            if (false === $id) {
                throw new UnprocessableEntityHttpException('The parent identifier must be a non-negative integer.');
            }

            $parameters['id'] = $id;
        }

        if (isset($parent['table'])) {
            if (!\is_string($parent['table']) || '' === $parent['table']) {
                throw new UnprocessableEntityHttpException('The parent table must be a non-empty string.');
            }

            $parameters['ptable'] = $parent['table'];
        }

        return $parameters;
    }

    private function runBackendAction(callable $action): Response
    {
        try {
            $action();
        } catch (ResponseException $exception) {
            if (!$exception->getResponse()->isRedirect()) {
                throw $exception;
            }

            return $exception->getResponse();
        }

        throw new UnprocessableEntityHttpException('The data container rejected the submitted fields.');
    }

    private function write(DataContainerRecord $record, array $parameters, callable $callback): mixed
    {
        try {
            return $this->connection->transactional(fn () => $this->run($record->table, $parameters, $callback));
        } finally {
            // A rollback must not leave records from the failed write in the static cache
            DataContainer::clearCurrentRecordCache(table: $record->table);
        }
    }

    private function run(string $table, array $parameters, callable $callback): mixed
    {
        $this->framework->initialize();

        return $this->requestSwitcher->runWithRequest($this->createRequest($table, $parameters), function () use ($table, $callback) {
            $this->framework->getAdapter(Controller::class)->loadDataContainer($table);
            $driver = $GLOBALS['TL_DCA'][$table]['config']['dataContainer'] ?? null;

            if (!\is_string($driver) || !is_a($driver, DC_Table::class, true)) {
                throw new NotFoundHttpException('The resource is not backed by a table data container.');
            }

            // Legacy actions and callbacks can output HTML directly, bypassing render().
            // Discard it to protect the API response, preserving any existing outer buffers.
            $level = ob_get_level();
            ob_start();

            try {
                return $callback($this->framework->createInstance($driver, [$table]));
            } finally {
                while (ob_get_level() > $level) {
                    ob_end_clean();
                }
            }
        });
    }

    private function createRequest(string $table, array $parameters): Request
    {
        $parent = $this->requestStack->getCurrentRequest();

        if (!$parent) {
            throw new \LogicException('Data container operations require a request context.');
        }

        $url = $this->urlAnalyzer->getEditUrl($parameters['ptable'] ?? $table, (int) (isset($parameters['ptable']) ? ($parameters['pid'] ?? $parameters['id'] ?? 0) : ($parameters['id'] ?? $parameters['pid'] ?? 0)));
        parse_str(parse_url($url ?? '', PHP_URL_QUERY) ?? '', $query);
        $parameters += ['table' => $table, 'do' => $query['do'] ?? null];
        $url = $this->urlGenerator->generate('contao_backend', $parameters);
        $method = \in_array($parameters['act'] ?? null, ['show', 'select'], true) ? 'GET' : 'POST';

        // Build a backend request instead of inheriting API routing or client
        // control parameters
        $request = Request::create($parent->getSchemeAndHttpHost().$url, $method, cookies: $parent->cookies->all(), server: array_intersect_key($parent->server->all(), array_flip(['SCRIPT_NAME', 'SCRIPT_FILENAME', 'SERVER_PROTOCOL'])));
        $request->attributes->add(['_route' => 'contao_backend', '_scope' => 'backend', '_contao_api' => true, '_locale' => $parent->getLocale()]);

        if ($parent->hasSession()) {
            $request->setSession($parent->getSession());
        }

        return $request;
    }
}
