services:
    contao_faq.listener.insert_tags:
        class: Contao\FaqBundle\EventListener\InsertTagsListener
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'
        public: true
