services:
    contao_faq.listener.insert_tags:
        class: Contao\FaqBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true

    contao_faq.listener.breadcrumb:
        class: Contao\FaqBundle\EventListener\BreadcrumbListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: contao.hook, hook: generateBreadcrumb }
        public: true
