services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@Contao\CoreBundle\Framework\ContaoFramework']]

    Contao\FaqBundle\Picker\FaqPickerProvider:
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@Symfony\Component\Security\Core\Security'
        tags:
            - { name: contao.picker_provider, priority: 64 }
