parameters:
    contao.dns_mapping: []

services:
    _defaults:
        autoconfigure: true

    contao.migration.collection:
        class: Contao\CoreBundle\Migration\MigrationCollection
        arguments:
            - []

    contao.migration.command_compiler:
        class: Contao\CoreBundle\Migration\CommandCompiler
        public: true
        arguments:
            - '@database_connection'
            - '@contao.doctrine.schema_provider'

    contao.migration.database_checks:
        class: Contao\CoreBundle\Migration\DatabaseMigrationChecks
        arguments:
            - '@database_connection'
            - '@contao.migration.command_compiler'
            - '@contao.doctrine.schema.mysql_innodb_row_size_calculator'

    contao.migration.database_runner:
        class: Contao\CoreBundle\Migration\DatabaseMigrationRunner
        arguments:
            - '@contao.migration.command_compiler'
            - '@contao.migration.collection'
            - '@contao.doctrine.backup_manager'

    contao.migration.environment.dns:
        class: Contao\CoreBundle\Migration\Environment\DnsMigration
        arguments:
            - '@database_connection'
            - '%contao.dns_mapping%'

    contao.migration.version_600.column_to_virtual:
        class: Contao\CoreBundle\Migration\Version600\ColumnToVirtualMigration
        arguments:
            - '@database_connection'

    contao.migration.version_600.default_dbafs_hashing_algorithm:
        class: Contao\CoreBundle\Migration\Version600\DefaultDbafsHashingAlgorithmMigration
        arguments:
            - '@database_connection'
            - '@contao.filesystem.dbafs.files'
            - md5

    contao.migration.version_600.output_encoding:
        class: Contao\CoreBundle\Migration\Version600\OutputEncodingMigration
        arguments:
            - '@database_connection'
