services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@Contao\CoreBundle\Framework\ContaoFramework']]

    contao.command.automator:
        class: Contao\CoreBundle\Command\AutomatorCommand
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'

    contao.command.debug_dca:
        class: Contao\CoreBundle\Command\DebugDcaCommand
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'

    contao.command.filesync:
        class: Contao\CoreBundle\Command\FilesyncCommand

    contao.command.install:
        class: Contao\CoreBundle\Command\InstallCommand
        arguments:
            - '%kernel.project_dir%'
            - '%contao.upload_path%'
            - '%contao.image.target_dir%'
        public: true

    contao.command.resize_images:
        class: Contao\CoreBundle\Command\ResizeImagesCommand
        arguments:
            - '@Contao\CoreBundle\Image\ImageFactory'
            - '@Contao\CoreBundle\Image\LegacyResizer'
            - '%contao.image.target_dir%'
            - '@contao.image.deferred_image_storage'
            - '@?filesystem'

    contao.command.symlinks:
        class: Contao\CoreBundle\Command\SymlinksCommand
        arguments:
            - '%kernel.project_dir%'
            - '%contao.upload_path%'
            - '%kernel.logs_dir%'
            - '@Contao\CoreBundle\Config\ResourceFinder'
            - '@event_dispatcher'
        public: true

    contao.command.user_password_command:
        class: Contao\CoreBundle\Command\UserPasswordCommand
        arguments:
            - '@Contao\CoreBundle\Framework\ContaoFramework'
            - '@database_connection'
            - '@security.encoder_factory'

    contao.command.version:
        class: Contao\CoreBundle\Command\VersionCommand
