services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [setContainer, ['@Psr\Container\ContainerInterface']]

        Contao\CoreBundle\Controller\AbstractController:
            tags:
                - { name: container.service_subscriber, id: contao.csrf.token_manager }

        Contao\CoreBundle\Controller\AbstractFragmentController:
            tags:
                - { name: container.service_subscriber, id: contao.twig.filesystem_loader }
                - { name: container.service_subscriber, id: contao.twig.interop.context_factory }

        Contao\CoreBundle\Controller\FrontendModule\AbstractFrontendModuleController:
            tags:
                - { name: container.service_subscriber, id: contao.csrf.token_manager }

    # We explicitly allow autowiring and FQCN service IDs in controllers
    Contao\CoreBundle\Controller\BackendController: ~

    Contao\CoreBundle\Controller\BackendCsvImportController:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@request_stack'
            - '@translator'
            - '%kernel.project_dir%'

    Contao\CoreBundle\Controller\BackendPreviewController:
        arguments:
            - '%contao.preview_script%'
            - '@contao.security.frontend_preview_authenticator'
            - '@event_dispatcher'
            - '@security.authorization_checker'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\BackendPreviewSwitchController:
        arguments:
            - '@contao.security.frontend_preview_authenticator'
            - '@contao.security.token_checker'
            - '@database_connection'
            - '@security.helper'
            - '@twig'
            - '@router'
            - '@contao.csrf.token_manager'
            - '%contao.backend.attributes%'
            - '%contao.backend.badge_title%'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\ContentElement\CodeController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\DownloadsController:
        arguments:
            - '@security.helper'
            - '@contao.filesystem.virtual.files'
            - '@contao.image.studio'
            - '@contao.filesystem.file_download_helper'
            - '@contao.image.preview_factory'
        tags:
            - { name: contao.content_element, category: files, type: download }
            - { name: contao.content_element, category: files, type: downloads }

    Contao\CoreBundle\Controller\ContentElement\ImagesController:
        arguments:
            - '@security.helper'
            - '@contao.filesystem.virtual.files'
            - '@contao.image.studio'
        tags:
            - { name: contao.content_element, category: media, type: image }
            - { name: contao.content_element, category: media, type: gallery }

    Contao\CoreBundle\Controller\ContentElement\HtmlController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\HeadlineController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\HyperlinkController:
        arguments:
            - '@contao.image.studio'
            - '@contao.insert_tag.parser'
        tags:
            - { name: contao.content_element, category: links }

    Contao\CoreBundle\Controller\ContentElement\ListController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\MarkdownController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\PlayerController:
        arguments:
            - '@contao.assets.assets_context'
        tags:
            - { name: contao.content_element, category: media }

    Contao\CoreBundle\Controller\ContentElement\TableController:
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\TeaserController:
        tags:
            - { name: contao.content_element, category: includes }

    Contao\CoreBundle\Controller\ContentElement\TemplateController:
        tags:
            - { name: contao.content_element, category: includes }

    Contao\CoreBundle\Controller\ContentElement\TextController:
        arguments:
            - '@contao.image.studio'
        tags:
            - { name: contao.content_element, category: texts }

    Contao\CoreBundle\Controller\ContentElement\ToplinkController:
        tags:
            - { name: contao.content_element, category: links }

    Contao\CoreBundle\Controller\ContentElement\VideoController:
        arguments:
            - '@contao.image.studio'
        tags:
            - { name: contao.content_element, category: media, type: vimeo }
            - { name: contao.content_element, category: media, type: youtube }

    Contao\CoreBundle\Controller\FaviconController:
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'
            - '@contao.cache.entity_tags'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\FrontendController:
        tags:
            - controller.service_arguments
            - { name: container.service_subscriber, id: contao.cron }
            - { name: container.service_subscriber, id: contao.csrf.token_manager }

    Contao\CoreBundle\Controller\FrontendModule\RootPageDependentModulesController:
        tags:
            - { name: contao.frontend_module, category: miscellaneous }

    Contao\CoreBundle\Controller\FrontendModule\TemplateController:
        tags:
            - { name: contao.frontend_module, category: miscellaneous }

    Contao\CoreBundle\Controller\FrontendModule\TwoFactorController:
        tags:
            - { name: contao.frontend_module, category: user }

    Contao\CoreBundle\Controller\ImagesController:
        public: true
        arguments:
            - '@contao.image.factory'
            - '@contao.image.resizer'
            - '%contao.image.target_dir%'
            - '@?filesystem'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\InsertTagsController:
        arguments:
            - '@contao.insert_tag.parser'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\Page\ErrorPageController:
        arguments:
            - '@contao.framework'

    Contao\CoreBundle\Controller\Page\RootPageController:
        arguments:
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: contao.error }

    Contao\CoreBundle\Controller\PreviewLinkController:
        arguments:
            - '@contao.security.frontend_preview_authenticator'
            - '@uri_signer'
            - '@database_connection'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\RobotsTxtController:
        arguments:
            - '@contao.framework'
            - '@event_dispatcher'
        tags:
            - controller.service_arguments

    Contao\CoreBundle\Controller\SitemapController:
        arguments:
            - '@contao.routing.page_registry'
        tags:
            - controller.service_arguments
