services:
    _defaults:
        autoconfigure: true
        public: true

    Contao\CoreBundle\Controller\Page\RootController:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '?@logger'
        tags:
            - { name: contao.page }
            - { name: monolog.logger, channel: contao }
