services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: false

    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        arguments:
            - '%contao.prepend_locale%'
            - '%contao.url_suffix%'
        tags:
            - routing.loader

    contao.routing.legacy_candidates:
        class: Contao\CoreBundle\Routing\Candidates\LegacyCandidates
        decorates: contao.routing.candidates
        arguments:
            - '%contao.prepend_locale%'
            - '%contao.url_suffix%'

    contao.routing.legacy_matcher:
        class: Contao\CoreBundle\Routing\Matcher\LegacyMatcher
        decorates: contao.routing.nested_matcher
        arguments:
            - '@contao.framework'
            - '@contao.routing.legacy_matcher.inner'
            - '%contao.url_suffix%'
            - '%contao.prepend_locale%'

    Contao\CoreBundle\EventListener\DataContainer\LegacyRoutingListener:
        arguments:
            - '@translator'
            - '%contao.prepend_locale%'
            - '%contao.url_suffix%'

    contao.routing.legacy_router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments:
            - '@router.request_context'
            - '@contao.routing.empty_matcher'
            - '@contao.routing.legacy_route_generator'
            - ''
            - '@event_dispatcher'
        tags:
            - { name: router }

    contao.routing.empty_matcher:
        class: Contao\CoreBundle\Routing\Matcher\UrlMatcher

    contao.routing.legacy_route_generator:
        class: Symfony\Cmf\Component\Routing\ProviderBasedGenerator
        arguments:
            - '@contao.routing.legacy_route_provider'
            - '@logger'

    contao.routing.legacy_route_provider:
        class: Contao\CoreBundle\Routing\LegacyRouteProvider
        arguments:
            - '@contao.routing.frontend_loader'
