services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Migration\MigrationCollection: ~

    Contao\CoreBundle\Migration\Version409\CeAccessMigration:
        arguments:
            - '@database_connection'
            - '@contao.framework'

    Contao\CoreBundle\Migration\Version410\OrderFieldMigration:
        arguments:
            - '@database_connection'
