services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Routing\Content\ArticleRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\Page\PageRouteFactory'

    Contao\CoreBundle\Routing\Content\PageRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\Page\PageRouteFactory'
