services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Routing\Content\ArticleRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\RouteFactory'

    Contao\CoreBundle\Routing\Content\PageRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\RouteFactory'
