services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Routing\Content\ArticleResolver:
        tags:
            - contao.content_resolver

    Contao\CoreBundle\Routing\Content\PageResolver:
        tags:
            - contao.content_resolver
