services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Routing\Content\ArticleRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\RouteFactory'

    Contao\CoreBundle\Routing\Content\PageRouteProvider:
        arguments:
            - '@Contao\CoreBundle\Routing\RouteFactory'

    Contao\CoreBundle\Routing\Page\PageRegistry:
        arguments:
            - '@database_connection'

    Contao\CoreBundle\Routing\RouteFactory:
        arguments:
            - '@Contao\CoreBundle\Routing\Page\PageRegistry'
            - !tagged_iterator contao.content_route_provider
