services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\Routing\Content\ArticleRouteProvider:
        arguments:
            - '@contao.routing.page_route_factory'

    Contao\CoreBundle\Routing\Content\PageRouteProvider:
        arguments:
            - '@contao.routing.page_route_factory'
