services:
    _defaults:
        autoconfigure: true

    Contao\CoreBundle\ContentRouting\ArticleUrlResolver:

    Contao\CoreBundle\ContentRouting\PageUrlResolver:

    Contao\CoreBundle\ContentRouting\RootPageProvider:
        arguments:
            - '@contao.framework'
            - '@database_connection'
