services:
    _defaults:
        autoconfigure: true
        autowire: true

    Contao\CoreBundle\Security\Voter\:
        resource: ../../Security/Voter/*

    # Backwards Compatibility
    contao.security.backend_access_voter: '@Contao\CoreBundle\Security\Voter\BackendAccessVoter'
