services:
    contao_comments.cron.purge_subscriptions:
        class: Contao\CommentsBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'
        tags:
            - contao.cronjob: { interval: daily }

    contao_comments.listener.data_container.add_comment_fields:
        class: Contao\CommentsBundle\EventListener\DataContainer\AddCommentFieldsListener
        arguments:
            - '%kernel.bundles%'
        tags:
            - contao.hook: { hook: loadDataContainer }
