services:
    _defaults:
        autoconfigure: true

    contao_oauth.client_generator:
        class: Contao\OAuthBundle\ClientGenerator
        arguments:
            - '@database_connection'
            - '@request_stack'
            - '@router' 

    contao_oauth.controller.frontend_module.oauth_connect:
        class: Contao\OAuthBundle\Controller\FrontendModule\OAuthConnectController
        arguments: 
            - '@router'
            - '@uri_signer'

    Contao\OAuthBundle\Controller\OAuthController:
        arguments:
            - '@database_connection'
            - '@contao_oauth.client_generator'
            - '@uri_signer'
        tags: ['controller.service_arguments']

    contao_oauth.listener.data_container.oauth_client_check:
        class: Contao\OAuthBundle\EventListener\DataContainer\OAuthClientCheckListener
        arguments:
            - '@database_connection'
            - '@translator'
            - '%kernel.bundles%'

    contao_oauth.listener.data_container.oauth_client_type_options:
        class: Contao\OAuthBundle\EventListener\DataContainer\OAuthClientTypeOptionsListener

    contao_oauth.listener.facebook_login:
        class: Contao\OAuthBundle\EventListener\FacebookLoginListener
        tags: ['kernel.event_listener']

    Contao\OAuthBundle\Security\OAuthAuthenticator:
        arguments:
            - '@contao_oauth.client_generator'
            - '@database_connection'
            - '@contao.framework'
            - '@contao.filesystem.virtual.files'
            - '@contao.slug'
            - '@event_dispatcher'
            - '@security.helper'

    Contao\OAuthBundle\ClientGenerator: '@contao_oauth.client_generator'
