services:
    contao_newsletter.cron.purge_subscriptions:
        class: Contao\NewsletterBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'
        tags:
            - { name: contao.cronjob, interval: daily }

    contao_newsletter.listener.sitemap:
        class: Contao\NewsletterBundle\EventListener\SitemapListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener
