name: PR

on:
    pull_request_target:
        types: [opened]

permissions:
    pull-requests: write

jobs:
    assign-pr:
        name: Assign
        runs-on: ubuntu-latest
        steps:
            - name: Assign the PR
              uses: toshimaru/auto-author-assign@v1.4.0
