name: CI

on:
    pull_request: ~
    push:
        branches:
            - 4.9
        tags:
            - 4.9.*
    schedule:
        - cron: 0 13 * * MON,TUE

jobs:
    test-php80:
        name: PHP 8.0
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: |
                  composer self-update --preview
                  composer install --no-interaction --no-suggest --ignore-platform-req=php

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@localhost:3306/contao_test
