name: CI

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'

    pull_request: ~

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  extension-csv: intl
                  coverage: pcov

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install the dependencies
              run: |
                  composer global require symfony/flex
                  composer install --no-interaction --no-suggest

            - name: Generate the coverage report
              run: php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=coverage --coverage-clover=clover.xml --colors=always

            - name: Upload the coverage report
              run: bash <(curl -s https://codecov.io/bash) -f clover.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  extension-csv: intl
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install the dependencies
              run: |
                  composer global require symfony/flex
                  composer install --no-interaction --no-suggest

            - name: Check the coding style
              run: |
                  PHP_CS_CONFIG=default vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run
                  PHP_CS_CONFIG=legacy vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run
                  PHP_CS_CONFIG=template vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run

            - name: Analyze the code
              run: vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php }}
                  extension-csv: intl
                  coverage: none

            - name: Install missing PHP 7.4 extensions
              if: matrix.php == '7.4'
              run: sudo apt-get install php7.4-gd php7.4-mbstring php7.4-mysql

            - name: Create the database
              run: mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install the dependencies
              run: |
                  composer global require symfony/flex
                  composer install --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@localhost:3306/contao_test

    prefer-lowest:
        name: Prefer Lowest
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  extension-csv: intl
                  coverage: none

            - name: Create the database
              run: mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install the dependencies
              run: |
                  composer global require symfony/flex
                  composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@localhost:3306/contao_test

    bundles:
        name: Bundles
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  extension-csv: intl
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Test the single bundles
              run: |
                  composer global require symfony/flex
                  bundles=(calendar-bundle core-bundle faq-bundle manager-bundle news-bundle)
                  for bundle in "${bundles[@]}"; do
                      cd $bundle
                      php -r '
                          $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
                          if ("contao/core-bundle" !== $data["name"]) {
                              $data["repositories"][0]["type"] = "path";
                              $data["repositories"][0]["url"] = "../core-bundle";
                          }
                          if ("contao/installation-bundle" !== $data["name"]) {
                              $data["repositories"][1]["type"] = "path";
                              $data["repositories"][1]["url"] = "../installation-bundle";
                          }
                          file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
                      '
                      COMPOSER_ROOT_VERSION=dev-${{ env.GITHUB_SHA }} composer install --no-interaction --no-suggest
                      vendor/bin/phpunit --colors=always
                      cd ..
                  done

    windows:
        name: Windows
        runs-on: windows-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  coverage: none

            - name: Enable the PHP extensions
              run: |
                echo extension=php_intl.dll >> C:\tools\php\php.ini
                echo extension=php_gd2.dll >> C:\tools\php\php.ini
                echo extension=php_fileinfo.dll >> C:\tools\php\php.ini

            - name: Adjust the Git autocrlf setting
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install the dependencies
              run: |
                  composer global require symfony/flex --no-progress
                  composer install --no-interaction --no-suggest --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit.bat --colors=always

    monorepo-split:
        name: Monorepo Split
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        needs: [coding-style, tests, prefer-lowest, bundles, windows]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Cache the monorepo split
              uses: actions/cache@v1
              with:
                path: $HOME/.monorepo-split-cache
                key: dev-${GITHUB_REF##*/}

            - name: Install the dependencies
              run: composer global require contao/monorepo-tools:dev-master

            - name: Validate the composer.json files
              run: $HOME/.composer/vendor/bin/monorepo-tools composer-json --validate --ansi

            - name: Split the monorepo
              run: $HOME/.composer/vendor/bin/monorepo-tools split ${GITHUB_REF##*/} --cache-dir $HOME/.monorepo-split-cache --ansi
              env:
                  GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
