name: CI

on:
    pull_request: ~
    push:
        branches:
            - 4.11
        tags:
            - 4.11.*
    schedule:
        - cron: 0 13 * * MON,TUE

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-18.04
        if: github.event_name != 'schedule'
        steps:
            - name: Test
              run: env
