name: CI

on:
    pull_request: ~
    push:
        branches:
            - 4.9
        tags:
            - 4.9.*
    schedule:
        - cron: 0 13 * * MON,TUE

permissions: read-all

jobs:
    monorepo-split:
        name: Monorepo Split
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: json, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1

            - name: Cache the monorepo split
              uses: actions/cache@v1
              with:
                  path: .monorepo-split-cache
                  key: dev-${GITHUB_REF##*/}

            - name: Install the dependencies
              run: composer global require contao/monorepo-tools:dev-main

            - name: Split the monorepo
              run: $HOME/.composer/vendor/bin/monorepo-tools split ${GITHUB_REF##*/}
              env:
                  GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
