name: PHP CS Fixer

on: [pull_request]

jobs:
    fix:
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@1.4.4
              with:
                  php-version: 7.3
                  extension-csv: intl

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run the CS fixer
              run: ./run php-cs-fixer

            - name: Commit the changes
              uses: stefanzweifel/git-auto-commit-action@v2.1.0
              with:
                  commit_message: Run the CS fixer
                  branch: ${{ github.head_ref }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
