name: Schedule

on:
    schedule:
        - cron: 0 13 * * MON,THU

permissions: read-all

jobs:
    inspect:
        name: Isolated tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin isolated-tests install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --extensions Contao\\CoreBundle\\Tests\\PhpunitExtension\\GlobalStateWatcher --colors=always

            - name: Run the unit tests isolated
              run: tools/isolated-tests/bin/run-tests-isolated --ansi

    windows:
        name: Windows
        runs-on: windows-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  ini-values: memory_limit=1G
                  coverage: none

            - name: Adjust the Git autocrlf setting
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v3

            - name: Get the Composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache the dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit.bat --colors=always

    cypress:
        name: Cypress
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Symfony CLI
              run: |
                  wget https://get.symfony.com/cli/installer -O - | bash
                  mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  npm update
                  composer install --working-dir=cypress/webspace --no-interaction --no-progress
                  symfony server:ca:install

            - name: Run the Cypress tests
              id: cypress
              run: |
                  symfony server:start --port=8765 --dir=cypress/webspace --daemon
                  npx cypress run --config-file cypress/cypress.config.js
                  symfony server:stop --dir=cypress/webspace
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test
                  TERM: xterm-256color

            - name: Upload videos
              uses: actions/upload-artifact@v2
              if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
              with:
                  name: Cypress videos
                  path: tools/cypress/videos
                  retention-days: 14
