name: Tests

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'

    pull_request: ~

jobs:
    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@1.5.1
              with:
                  php-version: ${{ matrix.php }}
                  extension-csv: intl
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit

#            - name: Run the functional tests
#              run: vendor/bin/phpunit --testsuite=functional

    windows:
        name: Windows
        runs-on: windows-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@1.5.1
              with:
                  php-version: 7.3
                  coverage: none

            - name: Enable PHP extensions
              run: |
                echo extension=php_fileinfo.dll >> C:\tools\php\php.ini
                echo extension=php_gd2.dll >> C:\tools\php\php.ini
                echo extension=php_intl.dll >> C:\tools\php\php.ini

            - name: Adjust the Git autocrlf settings
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 50

            - name: Install dependencies
              run: composer install --no-interaction --no-progress --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit.bat

    split:
        name: Split the monorepo
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        needs: [tests, windows]
        steps:
            - run: echo "Split the monorepo"
